### ISSUE TITLE
Change the background

### ISSUE THREAD

**Issue by PiotrSss** [adamkdean/gpt-unicorn#4]
IMO it doesn't make sense to present these generations on a white background.

Original

<img width="1201" alt="CleanShot 2023-04-23 at 11 33 24@2x" src="https://user-images.githubusercontent.com/1761204/233831749-3976b3c8-9bbc-418d-a80e-54a7a2dd91d8.png">

vs

<img width="1206" alt="CleanShot 2023-04-23 at 11 32 46@2x" src="https://user-images.githubusercontent.com/1761204/233831755-857bbb3d-f8f4-4216-b04b-b23df84e431c.png">

**Comment by adamkdean** [comment]
Fixed by https://github.com/adamkdean/gpt-unicorn/commit/e0afbc771966178a06d319c1c4a0b14e06d5329d
